# Generated by Django 5.0.2 on 2024-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Contact_table',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('details', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Register_table',
            },
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('city', models.CharField()),
                ('country', models.CharField()),
                ('postalcode', models.CharField()),
            ],
            options={
                'db_table': 'Userdetails_table',
            },
        ),
    ]
